baseURL = "http://hugo-faherne.s3-website-eu-west-1.amazonaws.com/"
languageCode = "en-us"
title = "Faherne's Blog"
theme = "whisper"
[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-faherne/?region=eu-west-1" #your bucket here

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
    
[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Tech Blog'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Finbarr's blog built on Hugo with Whisper Theme"
    meta_og_title = "Finbarr's Blog"
    meta_og_type = "website"
    meta_og_url = "http://hugo-faherne.s3-website-eu-west-1.amazonaws.com/"
    meta_og_image = "/images/Transparent Logo.png"
    meta_og_description = "Tech Blog"
    meta_twitter_card = "summary"
    meta_twitter_site = "@faherne"
    meta_twitter_creator = "@faherne"

  [params.logo]
      mobile = "/images/Original Logo.svg"
      standard  = "/images/Original Logo.svg"
